# A docker-compose file for running the TAMU Dialogue Act Classifier (TDAC)
# as a standalone python app

version: '3'

services:

  tamu_dialogue_act_classifier:
    image: tamu_dialogue_act_classifier:latest
    container_name: tamu_dialogue_act_classifier
    build: .
    environment:
      - PYTHONUNBUFFERED=1

    entrypoint: python tdac_mqtt.py --host host.docker.internal --port 1883
