# A Docker Compose file for running the TAMU dialogue act classifier web
# service as a standalone container.

version: '3'
services:
  tamu_dialogue_act_classifier:
    image: tamu_dialogue_act_classifier:latest
    container_name: tamu_dialogue_act_classifier
    build: .
    #    ports:
      # Change the line below if you want to use a different port mapping. The
      # format is "host_port:container_port".
      #  - "8000:8000"
    # entrypoint: dac_server:MESSAGE_BUS
    entrypoint: python dac_server.py

