# A Docker Compose file for running the TAMU dialogue act classifier 
# as a standalone python app

version: '3'

networks:
  asist_net:
   external: true

services:
  tamu_dialogue_act_classifier:
    image: tamu_dialogue_act_classifier:latest
    container_name: tamu_dialogue_act_classifier
    build: .
    environment:
      - PYTHONUNBUFFERED=1

    entrypoint: python dac_server.py
