#!/usr/bin/env bash

set -euo pipefail

# Script to download pretrained model

# Set the ROOT environment variable, assuming that the directory structure
# mirrors that of the git repository.
export ROOT="$(cd "$( dirname "${BASH_SOURCE[0]}" )/../" >/dev/null 2>&1 && pwd)"


MODEL_URL=http://vanga.sista.arizona.edu/tomcat/data/sequential_baseline.pt

pushd ${ROOT}/data > /dev/null
    curl -O $MODEL_URL
popd > /dev/null

echo "Pretrained model downloaded from ${MODEL_URL}"
