#!/usr/bin/env bash

set -euo pipefail

# Script to run the python TAMU dialogue act classification application

# Set the ROOT environment variable, assuming that the directory structure
# mirrors that of the git repository.
export ROOT="$(cd "$( dirname "${BASH_SOURCE[0]}" )/../" >/dev/null 2>&1 && pwd)"

pushd ${ROOT} > /dev/null
    python ../dac_server.py
popd > /dev/null
