#!/usr/bin/env bash

set -euo pipefail

# Script to run the python TAMU Dialogue Act Classifier (TDAC)

# Set the ROOT environment variable, assuming that the directory structure
# mirrors that of the git repository.
export ROOT="$(cd "$( dirname "${BASH_SOURCE[0]}" )/../" >/dev/null 2>&1 && pwd)"

echo "ROOT = $ROOT"

pushd ${ROOT} > /dev/null
    python tdac.py
popd > /dev/null
